import java.util.Arrays;

public class Chapter5 extends Chapter {
    public Chapter5() {
        super("Chapitre 5 : Fichiers WAR et EAR", Arrays.asList(
            new Question("Quel format est utilisé pour les applications web simples ?",
                new String[]{"EAR", "WAR", "JAR", "ZIP"},
                1,
                "WAR est utilisé pour les applications web."),
            new Question("Quel format supporte les modules EJB ?",
                new String[]{"WAR", "EAR", "JAR", "TAR"},
                1,
                "EAR est utilisé pour les applications d'entreprise avec EJB."),
            new Question("Que signifie WAR ?",
                new String[]{"Web Archive Resource", "Web Application Archive", "Web Application Resource", "Web Archive Application"},
                1,
                "WAR signifie Web Application Archive."),
            new Question("Que signifie EAR ?",
                new String[]{"Enterprise Application Resource", "Enterprise Archive", "Enterprise Application Runtime", "Enterprise Archive Resource"},
                1,
                "EAR signifie Enterprise Archive."),
            new Question("Quelle est la structure d'un fichier WAR ?",
                new String[]{"Uniquement des classes Java", "WEB-INF avec classes, lib, web.xml + ressources web", "Uniquement des fichiers HTML", "Uniquement web.xml"},
                1,
                "Un WAR contient WEB-INF (classes, lib, web.xml) et les ressources web (HTML, JSP, CSS, etc.)."),
            new Question("Un fichier EAR peut-il contenir plusieurs WAR ?",
                new String[]{"Non", "Oui", "Seulement un WAR", "Seulement des JAR"},
                1,
                "Un EAR peut contenir plusieurs modules WAR et EJB JAR."),
            new Question("Où se trouve le fichier web.xml dans un WAR ?",
                new String[]{"À la racine", "Dans WEB-INF/", "Dans META-INF/", "Dans classes/"},
                1,
                "web.xml se trouve dans le répertoire WEB-INF/ du fichier WAR."),
            new Question("Quelle est la différence entre WAR et JAR ?",
                new String[]{"Aucune différence", "WAR est pour web, JAR est générique", "JAR est plus grand", "WAR est plus ancien"},
                1,
                "WAR est spécialisé pour les applications web avec structure WEB-INF, JAR est un format générique."),
            new Question("Où sont placées les classes compilées dans un WAR ?",
                new String[]{"À la racine", "Dans WEB-INF/classes/", "Dans META-INF/", "Dans lib/"},
                1,
                "Les classes compilées sont placées dans WEB-INF/classes/ du fichier WAR."),
            new Question("Quel fichier décrit la structure d'un EAR ?",
                new String[]{"web.xml", "application.xml", "ear.xml", "deployment.xml"},
                1,
                "application.xml est le descripteur de déploiement qui décrit la structure d'un EAR."),
            new Question("Peut-on déployer un WAR directement sur un serveur ?",
                new String[]{"Non, il faut un EAR", "Oui, un WAR peut être déployé seul", "Non, il faut compiler d'abord", "Oui, mais seulement sur Tomcat"},
                1,
                "Un WAR peut être déployé directement sur un serveur d'application sans être dans un EAR."),
            new Question("Quelle est la structure d'un EAR ?",
                new String[]{"Uniquement des WAR", "WAR, EJB JAR, et application.xml", "Uniquement des JAR", "Uniquement application.xml"},
                1,
                "Un EAR contient des modules WAR, des modules EJB JAR, et le fichier application.xml."),
            new Question("Où se trouve application.xml dans un EAR ?",
                new String[]{"À la racine", "Dans WEB-INF/", "Dans META-INF/", "Dans classes/"},
                2,
                "application.xml se trouve dans META-INF/ du fichier EAR."),
            new Question("Quel format est utilisé pour les bibliothèques partagées dans un EAR ?",
                new String[]{"WAR", "JAR", "EAR", "ZIP"},
                1,
                "Les bibliothèques partagées sont généralement dans des JAR dans le répertoire lib/ de l'EAR."),
            new Question("Que contient le dossier WEB-INF/lib/ dans un WAR ?",
                new String[]{"Classes compilées", "Fichiers JAR de dépendances", "Fichiers de configuration", "Images et CSS"},
                1,
                "WEB-INF/lib/ contient les fichiers JAR des bibliothèques externes dont l'application dépend."),
            new Question("Les fichiers dans WEB-INF/ sont-ils accessibles directement via URL ?",
                new String[]{"Oui, tous les fichiers", "Non, WEB-INF est protégé", "Seulement web.xml", "Seulement les classes"},
                1,
                "Le dossier WEB-INF/ est protégé et son contenu n'est pas accessible directement via une URL par les clients."),
            new Question("Où placer les fichiers statiques (HTML, CSS, JS) dans un WAR ?",
                new String[]{"Dans WEB-INF/", "À la racine du WAR ou dans des sous-dossiers publics", "Dans classes/", "Dans META-INF/"},
                1,
                "Les fichiers statiques sont placés à la racine du WAR ou dans des dossiers publics pour être accessibles via URL."),
            new Question("Que signifie JAR ?",
                new String[]{"Java Archive Resource", "Java Archive", "Java Application Resource", "Java Application Runtime"},
                1,
                "JAR signifie Java Archive, un format de fichier pour regrouper des classes Java."),
            new Question("Quelle extension a un fichier EJB module ?",
                new String[]{"WAR", "EJB", "JAR", "EAR"},
                2,
                "Un module EJB est packagé dans un fichier JAR avec les métadonnées EJB."),
            new Question("Comment créer un fichier WAR avec Maven ?",
                new String[]{"mvn war", "mvn package", "mvn build", "mvn create-war"},
                1,
                "La commande 'mvn package' compile et crée le fichier WAR dans le dossier target/.")
        ));
    }
}