import java.util.Arrays;

public class Chapter10 extends Chapter {
    public Chapter10() {
        super("Chapitre 10 : Cycle de Vie des Requêtes HTTP", Arrays.asList(
            new Question("Quelle méthode gère les requêtes GET ?",
                new String[]{"doPost()", "doGet()", "init()", "service()"},
                1,
                "doGet() gère les requêtes HTTP GET."),
            new Question("Quel objet contient les données de la requête ?",
                new String[]{"HttpServletResponse", "HttpRequest", "HttpServletRequest", "RequestData"},
                2,
                "HttpServletRequest contient les informations de la requête."),
            new Question("Quelle méthode est appelée en premier lors de l'initialisation d'un servlet ?",
                new String[]{"doGet()", "init()", "service()", "destroy()"},
                1,
                "init() est appelée une seule fois lors de l'initialisation du servlet."),
            new Question("Quelle méthode gère les requêtes POST ?",
                new String[]{"doGet()", "doPost()", "doPut()", "doDelete()"},
                1,
                "doPost() gère les requêtes HTTP POST."),
            new Question("Quel objet est utilisé pour envoyer la réponse au client ?",
                new String[]{"HttpServletRequest", "HttpServletResponse", "Response", "OutputStream"},
                1,
                "HttpServletResponse est utilisé pour construire et envoyer la réponse HTTP."),
            new Question("Quelle méthode est appelée à la destruction du servlet ?",
                new String[]{"init()", "service()", "destroy()", "finalize()"},
                2,
                "destroy() est appelée une fois lorsque le conteneur détruit le servlet."),
            new Question("Dans quel ordre les méthodes sont-elles appelées ?",
                new String[]{"init() -> service() -> destroy()", "service() -> init() -> destroy()", "destroy() -> init() -> service()", "init() -> destroy() -> service()"},
                0,
                "L'ordre est : init() (une fois), puis service()/doGet()/doPost() (plusieurs fois), puis destroy() (une fois)."),
            new Question("Quelle méthode est appelée pour chaque requête HTTP ?",
                new String[]{"init()", "service()", "destroy()", "doGet()"},
                1,
                "service() est appelée pour chaque requête et délègue à doGet(), doPost(), etc."),
            new Question("Quand la méthode init() est-elle appelée ?",
                new String[]{"À chaque requête", "Une seule fois au démarrage du servlet", "À la destruction", "Jamais"},
                1,
                "init() est appelée une seule fois lorsque le conteneur charge le servlet pour la première fois."),
            new Question("Quelle interface doit implémenter un servlet ?",
                new String[]{"Servlet", "HttpServlet", "GenericServlet", "Toutes les réponses ci-dessus"},
                0,
                "Un servlet implémente l'interface Servlet, généralement via HttpServlet."),
            new Question("Quelle méthode gère les requêtes PUT ?",
                new String[]{"doGet()", "doPost()", "doPut()", "doDelete()"},
                2,
                "doPut() gère les requêtes HTTP PUT pour mettre à jour des ressources."),
            new Question("Quelle méthode gère les requêtes DELETE ?",
                new String[]{"doGet()", "doPost()", "doPut()", "doDelete()"},
                3,
                "doDelete() gère les requêtes HTTP DELETE pour supprimer des ressources."),
            new Question("Quel objet permet d'accéder au contexte de l'application ?",
                new String[]{"HttpServletRequest", "ServletContext", "HttpSession", "HttpServletResponse"},
                1,
                "ServletContext fournit l'accès aux informations sur l'application web."),
            new Question("Quelle méthode est appelée si le timeout de session expire ?",
                new String[]{"destroy()", "sessionInvalidated()", "timeout()", "expire()"},
                1,
                "sessionInvalidated() est appelée dans un HttpSessionListener lorsque la session expire."),
            new Question("Combien de fois init() est-elle appelée pour un servlet ?",
                new String[]{"À chaque requête", "Une seule fois", "Deux fois", "Jamais"},
                1,
                "init() est appelée une seule fois lors du chargement initial du servlet par le conteneur."),
            new Question("Que fait la méthode service() ?",
                new String[]{"Initialise le servlet", "Route les requêtes vers doGet(), doPost(), etc.", "Détruit le servlet", "Gère les sessions"},
                1,
                "service() examine le type de requête HTTP et appelle la méthode appropriée (doGet, doPost, etc.)."),
            new Question("Peut-on redéfinir la méthode service() ?",
                new String[]{"Non, jamais", "Oui, mais ce n'est pas recommandé", "Oui, c'est obligatoire", "Non, c'est impossible"},
                1,
                "On peut redéfinir service(), mais il est préférable de redéfinir doGet(), doPost(), etc."),
            new Question("Quelle méthode permet de récupérer la configuration du servlet ?",
                new String[]{"getConfig()", "getServletConfig()", "getConfiguration()", "getSettings()"},
                1,
                "getServletConfig() retourne l'objet ServletConfig contenant les paramètres d'initialisation."),
            new Question("Quand destroy() est-elle appelée ?",
                new String[]{"À chaque requête", "Quand le conteneur arrête le servlet", "Au démarrage", "Jamais"},
                1,
                "destroy() est appelée une fois quand le conteneur arrête ou redéploie le servlet."),
            new Question("Quelle méthode HttpServlet doit-on redéfinir pour gérer les formulaires ?",
                new String[]{"doGet()", "doPost()", "service()", "init()"},
                1,
                "doPost() est généralement utilisée pour gérer les soumissions de formulaires HTML.")
        ));
    }
}