import java.util.Arrays;

public class Chapter7 extends Chapter {
    public Chapter7() {
        super("Chapitre 7 : Configuration Session et Contexte", Arrays.asList(
            new Question("Quelle balise définit le timeout de session ?",
                new String[]{"<session-config>", "<timeout>", "<session>", "<config>"},
                0,
                "<session-config> définit la durée de la session."),
            new Question("Quelle balise définit les paramètres globaux ?",
                new String[]{"<context-param>", "<global-param>", "<init-param>", "<web-param>"},
                0,
                "<context-param> définit des valeurs globales pour l'application."),
            new Question("Dans quelle balise se trouve la définition du timeout de session ?",
                new String[]{"<timeout>", "<session-timeout>", "<session-config>", "<session>"},
                2,
                "Le timeout est défini dans <session-config> avec la balise <session-timeout>."),
            new Question("Quelle est l'unité de mesure du timeout de session dans web.xml ?",
                new String[]{"Secondes", "Millisecondes", "Minutes", "Heures"},
                2,
                "Le timeout de session est défini en minutes dans web.xml."),
            new Question("Comment accéder aux paramètres de contexte dans un servlet ?",
                new String[]{"getInitParameter()", "getServletContext().getInitParameter()", "getContextParam()", "getGlobalParam()"},
                1,
                "On utilise getServletContext().getInitParameter() pour lire les context-param."),
            new Question("Quelle balise définit les erreurs personnalisées ?",
                new String[]{"<error>", "<error-page>", "<exception>", "<error-handler>"},
                1,
                "<error-page> mappe les codes d'erreur HTTP ou exceptions à des pages personnalisées."),
            new Question("Quelle est la portée des context-param ?",
                new String[]{"Par servlet", "Globale à l'application", "Par session", "Par requête"},
                1,
                "Les context-param sont globaux à toute l'application web."),
            new Question("Quelle est la valeur par défaut du timeout de session ?",
                new String[]{"10 minutes", "30 minutes", "Dépend du serveur", "5 minutes"},
                2,
                "Le timeout par défaut dépend de la configuration du serveur d'application."),
            new Question("Comment obtenir la session dans un servlet ?",
                new String[]{"new HttpSession()", "request.getSession()", "createSession()", "getHttpSession()"},
                1,
                "request.getSession() retourne l'objet HttpSession associé à la requête."),
            new Question("Quelle balise définit les listeners d'événements ?",
                new String[]{"<listener>", "<event-listener>", "<web-listener>", "<app-listener>"},
                0,
                "<listener> déclare un listener pour écouter les événements de l'application."),
            new Question("Quelle est la différence entre init-param et context-param ?",
                new String[]{"Aucune différence", "init-param est pour un servlet, context-param est global", "context-param est pour un servlet", "init-param est global"},
                1,
                "init-param est spécifique à un servlet, tandis que context-param est global à toute l'application."),
            new Question("Comment définir un code d'erreur personnalisé dans web.xml ?",
                new String[]{"<error-code>", "<error-page> avec <error-code>", "<custom-error>", "<http-error>"},
                1,
                "<error-page> avec <error-code> permet de mapper un code HTTP à une page personnalisée."),
            new Question("Quelle balise définit les types MIME ?",
                new String[]{"<mime-type>", "<mime-mapping>", "<content-type>", "<type>"},
                1,
                "<mime-mapping> associe une extension de fichier à un type MIME."),
            new Question("Quelle est la portée d'une session HTTP ?",
                new String[]{"Globale à l'application", "Par utilisateur", "Par requête", "Par servlet"},
                1,
                "Une session HTTP est unique par utilisateur et persiste entre plusieurs requêtes."),
            new Question("Quel listener permet de détecter la création d'une session ?",
                new String[]{"HttpSessionListener", "SessionListener", "HttpListener", "WebSessionListener"},
                0,
                "HttpSessionListener avec la méthode sessionCreated() permet de détecter la création d'une session."),
            new Question("Que se passe-t-il quand le timeout de session expire ?",
                new String[]{"Rien", "La session est automatiquement invalidée", "L'utilisateur est déconnecté immédiatement", "Le serveur redémarre"},
                1,
                "Quand le timeout expire, le conteneur invalide automatiquement la session et libère ses ressources."),
            new Question("Comment définir un paramètre de contexte dans web.xml ?",
                new String[]{"<context-param> avec <param-name> et <param-value>", "<param> avec <name> et <value>", "<global-param>", "<init-param>"},
                0,
                "On utilise <context-param> contenant <param-name> et <param-value> pour définir des paramètres globaux."),
            new Question("Quelle interface permet d'écouter les événements d'attributs de session ?",
                new String[]{"HttpSessionListener", "HttpSessionAttributeListener", "SessionAttributeListener", "AttributeListener"},
                1,
                "HttpSessionAttributeListener permet de détecter l'ajout, la suppression ou la modification d'attributs de session."),
            new Question("Comment mapper une exception Java à une page d'erreur ?",
                new String[]{"<error-page> avec <exception-type>", "<exception-mapping>", "<error-handler>", "<exception-page>"},
                0,
                "<error-page> avec <exception-type> permet de rediriger vers une page spécifique quand une exception se produit."),
            new Question("Quel listener permet de détecter le démarrage de l'application ?",
                new String[]{"ApplicationListener", "ServletContextListener", "WebAppListener", "StartupListener"},
                1,
                "ServletContextListener avec contextInitialized() est appelé au démarrage de l'application web.")
        ));
    }
}