import java.util.Arrays;

public class Chapter3 extends Chapter {
    public Chapter3() {
        super("Chapitre 3 : Conteneurs", Arrays.asList(
            new Question("Quel conteneur gère les Servlets ?",
                new String[]{"Conteneur EJB", "Conteneur Web", "Conteneur JPA", "Conteneur JMS"},
                1,
                "Le Conteneur Web gère les Servlets et les JSP."),
            new Question("Quel serveur supporte à la fois les conteneurs Web et EJB ?",
                new String[]{"Tomcat", "GlassFish", "Jetty", "Apache"},
                1,
                "GlassFish est un serveur Java EE complet."),
            new Question("Quel est le rôle d'un conteneur ?",
                new String[]{"Stocker des données", "Fournir des services d'exécution", "Créer des interfaces", "Gérer les bases de données"},
                1,
                "Un conteneur fournit des services d'exécution comme le cycle de vie et l'injection de dépendances."),
            new Question("Quel conteneur gère les Enterprise JavaBeans ?",
                new String[]{"Conteneur Web", "Conteneur EJB", "Conteneur JPA", "Conteneur JMS"},
                1,
                "Le Conteneur EJB gère le cycle de vie et les services pour les EJB."),
            new Question("Tomcat est-il un conteneur complet JEE ?",
                new String[]{"Oui", "Non, seulement web", "Oui, avec EJB", "Non, c'est un serveur de base de données"},
                1,
                "Tomcat est uniquement un conteneur web, il ne supporte pas EJB."),
            new Question("Quels services le conteneur web fournit-il ?",
                new String[]{"Gestion des transactions", "Cycle de vie des Servlets, sécurité, sessions", "Accès base de données", "Messagerie"},
                1,
                "Le conteneur web gère le cycle de vie des Servlets, la sécurité, les sessions HTTP, etc."),
            new Question("Quelle est la différence entre un conteneur web et un conteneur EJB ?",
                new String[]{"Aucune différence", "Le conteneur web gère Servlets/JSP, le conteneur EJB gère les beans métier", "Le conteneur EJB est plus rapide", "Le conteneur web est plus sécurisé"},
                1,
                "Le conteneur web gère les composants web (Servlets/JSP), tandis que le conteneur EJB gère les beans métier."),
            new Question("Quel conteneur gère le cycle de vie des Servlets ?",
                new String[]{"Conteneur EJB", "Conteneur Web", "Conteneur JPA", "Conteneur JMS"},
                1,
                "Le Conteneur Web gère l'initialisation, l'exécution et la destruction des Servlets."),
            new Question("Quels services le conteneur EJB fournit-il ?",
                new String[]{"Gestion des transactions, sécurité, pooling", "Gestion HTTP", "Gestion des sessions web", "Gestion des fichiers"},
                0,
                "Le conteneur EJB fournit la gestion des transactions, la sécurité, le pooling de connexions, etc."),
            new Question("Qu'est-ce qu'un serveur d'application complet ?",
                new String[]{"Un serveur avec seulement un conteneur web", "Un serveur avec conteneurs web et EJB", "Un serveur de base de données", "Un serveur de fichiers"},
                1,
                "Un serveur d'application complet supporte à la fois les conteneurs web et EJB."),
            new Question("Quel conteneur est nécessaire pour exécuter des Servlets ?",
                new String[]{"Conteneur EJB", "Conteneur Web", "Conteneur JPA", "Aucun conteneur"},
                1,
                "Les Servlets nécessitent un Conteneur Web pour s'exécuter."),
            new Question("Quelle est la responsabilité principale d'un conteneur ?",
                new String[]{"Stocker les données", "Fournir l'environnement d'exécution et les services", "Créer l'interface utilisateur", "Gérer le réseau"},
                1,
                "Un conteneur fournit l'environnement d'exécution et les services nécessaires aux composants."),
            new Question("Peut-on avoir plusieurs conteneurs dans un serveur d'application ?",
                new String[]{"Non, un seul conteneur", "Oui, plusieurs conteneurs peuvent coexister", "Oui, mais seulement 2", "Non, c'est impossible"},
                1,
                "Un serveur d'application complet peut avoir plusieurs conteneurs (web, EJB, etc.) fonctionnant ensemble."),
            new Question("Quel conteneur gère les JSP ?",
                new String[]{"Conteneur EJB", "Conteneur Web", "Conteneur JPA", "Conteneur JMS"},
                1,
                "Le Conteneur Web compile et exécute les JSP, qui sont converties en Servlets."),
            new Question("Qu'est-ce que l'injection de dépendances ?",
                new String[]{"Une erreur de code", "Un service fourni par le conteneur pour injecter des ressources", "Une méthode de compilation", "Un type de base de données"},
                1,
                "L'injection de dépendances est un service du conteneur qui fournit automatiquement les ressources nécessaires aux composants."),
            new Question("Quel service de conteneur gère les transactions ?",
                new String[]{"Conteneur Web", "Conteneur EJB", "Les deux", "Aucun des deux"},
                1,
                "Le Conteneur EJB gère les transactions déclaratives pour les beans métier."),
            new Question("Que signifie 'cycle de vie géré par conteneur' ?",
                new String[]{"Le développeur crée et détruit les objets", "Le conteneur gère la création, l'initialisation et la destruction", "Les objets vivent indéfiniment", "C'est une erreur"},
                1,
                "Le conteneur contrôle quand les composants sont créés, initialisés et détruits selon leur cycle de vie."),
            new Question("Quel conteneur gère le pooling des EJB ?",
                new String[]{"Conteneur Web", "Conteneur EJB", "Conteneur JPA", "Aucun"},
                1,
                "Le Conteneur EJB gère un pool d'instances d'EJB pour optimiser les performances et les ressources."),
            new Question("Quelle est la relation entre un serveur et un conteneur ?",
                new String[]{"C'est la même chose", "Le serveur héberge un ou plusieurs conteneurs", "Le conteneur héberge le serveur", "Ils sont indépendants"},
                1,
                "Un serveur d'application héberge et exécute un ou plusieurs conteneurs (web, EJB, etc.)."),
            new Question("Quel avantage offre un conteneur par rapport à une application standalone ?",
                new String[]{"Plus rapide", "Services d'entreprise intégrés (transactions, sécurité, pooling)", "Plus simple", "Moins de code"},
                1,
                "Les conteneurs fournissent des services d'entreprise complexes que le développeur n'a pas besoin d'implémenter manuellement.")
        ));
    }
}