import java.util.Arrays;

public class Chapter11 extends Chapter {
    public Chapter11() {
        super("Chapitre 11 : Requêtes HTTP et Paramètres", Arrays.asList(
            new Question("Comment récupérer un paramètre de requête dans un servlet ?",
                new String[]{"getAttribute()", "getParameter()", "getValue()", "getRequestParam()"},
                1,
                "getParameter() récupère un paramètre de la requête HTTP."),
            new Question("Quelle méthode récupère tous les paramètres d'une requête ?",
                new String[]{"getAllParameters()", "getParameterMap()", "getParameters()", "getRequestMap()"},
                1,
                "getParameterMap() retourne une Map de tous les paramètres de la requête."),
            new Question("Comment récupérer l'URL complète de la requête ?",
                new String[]{"getURL()", "getRequestURL()", "getPath()", "getUri()"},
                1,
                "getRequestURL() retourne l'URL complète de la requête."),
            new Question("Quelle méthode récupère la méthode HTTP utilisée (GET, POST) ?",
                new String[]{"getMethod()", "getHttpMethod()", "getRequestMethod()", "getType()"},
                0,
                "getMethod() retourne la méthode HTTP de la requête (GET, POST, etc.)."),
            new Question("Comment récupérer l'adresse IP du client ?",
                new String[]{"getClientIP()", "getRemoteAddr()", "getIP()", "getClientAddress()"},
                1,
                "getRemoteAddr() retourne l'adresse IP du client."),
            new Question("Quelle méthode récupère les en-têtes HTTP ?",
                new String[]{"getHeader()", "getHttpHeader()", "getRequestHeader()", "getHeaderValue()"},
                0,
                "getHeader() récupère la valeur d'un en-tête HTTP spécifique."),
            new Question("Comment accéder aux attributs de la requête ?",
                new String[]{"getAttribute()", "getParameter()", "getValue()", "getRequestAttribute()"},
                0,
                "getAttribute() récupère un attribut stocké dans la requête (différent des paramètres)."),
            new Question("Quelle est la différence entre getParameter() et getAttribute() ?",
                new String[]{"Aucune différence", "getParameter() lit les données de la requête, getAttribute() lit les attributs stockés", "getAttribute() lit les paramètres", "getParameter() lit les attributs"},
                1,
                "getParameter() lit les paramètres de la requête HTTP, getAttribute() lit les attributs stockés dans la requête."),
            new Question("Comment récupérer plusieurs valeurs pour un même paramètre ?",
                new String[]{"getParameter()", "getParameterValues()", "getAllParameters()", "getParameters()"},
                1,
                "getParameterValues() retourne un tableau de valeurs pour un paramètre qui peut avoir plusieurs valeurs."),
            new Question("Comment obtenir le chemin de la requête (sans query string) ?",
                new String[]{"getRequestURL()", "getRequestURI()", "getPath()", "getQueryString()"},
                1,
                "getRequestURI() retourne le chemin de la requête sans le query string."),
            new Question("Comment obtenir la query string de la requête ?",
                new String[]{"getQuery()", "getQueryString()", "getParameters()", "getURL()"},
                1,
                "getQueryString() retourne la partie query string de l'URL (après le ?)."),
            new Question("Quelle méthode récupère le nom du serveur ?",
                new String[]{"getServerName()", "getHost()", "getServer()", "getDomain()"},
                0,
                "getServerName() retourne le nom d'hôte du serveur."),
            new Question("Comment obtenir le port du serveur ?",
                new String[]{"getPort()", "getServerPort()", "getPortNumber()", "getServerPortNumber()"},
                1,
                "getServerPort() retourne le numéro de port sur lequel la requête a été reçue."),
            new Question("Quelle méthode récupère le protocole HTTP utilisé ?",
                new String[]{"getProtocol()", "getHttpProtocol()", "getScheme()", "getHttpScheme()"},
                0,
                "getProtocol() retourne le nom et la version du protocole (ex: HTTP/1.1)."),
            new Question("Comment récupérer le contexte de l'application (context path) ?",
                new String[]{"getContext()", "getContextPath()", "getApplicationPath()", "getPath()"},
                1,
                "getContextPath() retourne le préfixe de chemin de l'application (ex: /monapp)."),
            new Question("Quelle méthode retourne tous les noms d'en-têtes de la requête ?",
                new String[]{"getHeaders()", "getHeaderNames()", "getAllHeaders()", "getHeaderList()"},
                1,
                "getHeaderNames() retourne une énumération de tous les noms d'en-têtes HTTP."),
            new Question("Comment obtenir le User-Agent du client ?",
                new String[]{"getUserAgent()", "getHeader(\"User-Agent\")", "getClientInfo()", "getBrowser()"},
                1,
                "getHeader(\"User-Agent\") retourne l'en-tête User-Agent contenant les infos sur le navigateur du client."),
            new Question("Quelle méthode permet de stocker un attribut dans la requête ?",
                new String[]{"setParameter()", "setAttribute()", "putAttribute()", "addAttribute()"},
                1,
                "setAttribute() stocke un objet dans la requête, accessible via getAttribute()."),
            new Question("Comment obtenir le chemin du servlet appelé (servlet path) ?",
                new String[]{"getServlet()", "getServletPath()", "getPath()", "getServletURI()"},
                1,
                "getServletPath() retourne la partie du chemin correspondant au mapping du servlet."),
            new Question("Quelle méthode retourne le corps de la requête pour lire des données binaires ?",
                new String[]{"getInputStream()", "getReader()", "getBody()", "getData()"},
                0,
                "getInputStream() retourne un ServletInputStream pour lire le corps de la requête sous forme binaire.")
        ));
    }
}