import java.util.Arrays;

public class Chapter8 extends Chapter {
    public Chapter8() {
        super("Chapitre 8 : Structure du Projet", Arrays.asList(
            new Question("Où sont stockés les fichiers source Java ?",
                new String[]{"/lib/", "/src/", "/WEB-INF/", "/build/"},
                1,
                "/src/ contient le code source Java."),
            new Question("Quel dossier contient les classes compilées ?",
                new String[]{"/classes/", "/src/", "/lib/", "/build/"},
                3,
                "/build/ contient la sortie compilée."),
            new Question("Où se trouvent les fichiers JSP dans un projet web ?",
                new String[]{"Dans /src/", "À la racine ou dans /WEB-INF/", "Dans /lib/", "Dans /classes/"},
                1,
                "Les JSP sont généralement à la racine du WAR ou dans /WEB-INF/ pour la sécurité."),
            new Question("Où sont placées les bibliothèques externes (JAR) ?",
                new String[]{"/src/", "/WEB-INF/lib/", "/lib/", "/classes/"},
                1,
                "Les bibliothèques JAR externes sont placées dans /WEB-INF/lib/."),
            new Question("Où se trouve le fichier web.xml dans un projet Maven ?",
                new String[]{"src/main/java", "src/main/webapp/WEB-INF/", "src/main/resources", "src/test"},
                1,
                "web.xml se trouve dans src/main/webapp/WEB-INF/ pour un projet Maven."),
            new Question("Quel dossier contient les ressources statiques (CSS, images) ?",
                new String[]{"/WEB-INF/", "À la racine ou dans un dossier public", "/classes/", "/lib/"},
                1,
                "Les ressources statiques sont généralement à la racine du WAR ou dans un dossier public."),
            new Question("Quelle est la structure standard d'un WAR déployé ?",
                new String[]{"Uniquement des classes", "WEB-INF/ (classes, lib, web.xml) + ressources web", "Uniquement web.xml", "Uniquement des JSP"},
                1,
                "Un WAR contient WEB-INF/ avec les classes, lib, web.xml, plus les ressources web à la racine."),
            new Question("Où sont placés les fichiers de configuration dans un projet Maven ?",
                new String[]{"src/main/java", "src/main/resources", "src/config", "src/conf"},
                1,
                "Les fichiers de configuration (properties, XML) sont dans src/main/resources."),
            new Question("Quel dossier contient les fichiers de test dans un projet Maven ?",
                new String[]{"src/test/java", "test/", "src/tests", "tests/"},
                0,
                "src/test/java contient les classes de test dans un projet Maven."),
            new Question("Où sont placés les fichiers statiques (CSS, JS) dans un projet web ?",
                new String[]{"WEB-INF/", "Dans un dossier public (ex: css/, js/)", "Dans classes/", "Dans lib/"},
                1,
                "Les fichiers statiques sont généralement dans des dossiers publics à la racine du WAR."),
            new Question("Quelle est la différence entre /WEB-INF/ et la racine du WAR ?",
                new String[]{"Aucune différence", "WEB-INF est protégé, la racine est accessible publiquement", "La racine est protégée", "WEB-INF contient seulement web.xml"},
                1,
                "WEB-INF est protégé et non accessible directement, la racine contient les ressources publiques."),
            new Question("Où sont compilées les classes Java dans un projet Maven ?",
                new String[]{"src/", "target/classes/", "build/", "out/"},
                1,
                "Maven compile les classes dans target/classes/ par défaut."),
            new Question("Quel fichier décrit les dépendances Maven ?",
                new String[]{"build.xml", "pom.xml", "dependencies.xml", "config.xml"},
                1,
                "pom.xml contient la section <dependencies> qui liste toutes les dépendances."),
            new Question("Quelle est la structure recommandée pour un projet JEE ?",
                new String[]{"Tout dans un seul dossier", "Séparation claire des couches (web, métier, données)", "Uniquement des servlets", "Uniquement des JSP"},
                1,
                "Une bonne structure sépare les couches : web (Servlets/JSP), métier (EJB/Beans), données (JPA/DAO)."),
            new Question("Où Maven stocke-t-il le fichier WAR généré ?",
                new String[]{"src/", "target/", "build/", "dist/"},
                1,
                "Maven génère le fichier WAR dans le dossier target/ après 'mvn package'."),
            new Question("Quel dossier contient les ressources de test dans Maven ?",
                new String[]{"src/test/resources", "src/test/config", "test/resources", "resources/test"},
                0,
                "src/test/resources contient les fichiers de configuration et ressources pour les tests."),
            new Question("Comment Maven gère-t-il les dépendances transitives ?",
                new String[]{"Il les ignore", "Il les télécharge automatiquement", "Il affiche une erreur", "Il faut les ajouter manuellement"},
                1,
                "Maven télécharge automatiquement les dépendances transitives (dépendances de vos dépendances)."),
            new Question("Où se trouve le fichier META-INF/MANIFEST.MF dans un WAR ?",
                new String[]{"À la racine", "Dans WEB-INF/", "Dans META-INF/", "Dans classes/"},
                2,
                "Le fichier MANIFEST.MF se trouve dans le dossier META-INF/ du WAR."),
            new Question("Quelle convention de nommage Maven utilise pour les packages ?",
                new String[]{"Tout en minuscules", "groupId inversé + artifactId", "CamelCase", "snake_case"},
                1,
                "Maven utilise la convention groupId inversé (ex: com.example) + artifactId pour les packages."),
            new Question("Quel dossier contient la documentation générée par Maven ?",
                new String[]{"docs/", "target/site/", "site/", "doc/"},
                1,
                "Maven génère la documentation (javadoc, rapports) dans target/site/.")
        ));
    }
}