import java.util.Arrays;

public class Chapter1 extends Chapter {
    public Chapter1() {
        super("Chapitre 1 : Introduction à JEE", Arrays.asList(
            new Question("Que signifie JEE ?",
                new String[]{"Java Easy Edition", "Java Enterprise Edition", "Java Embedded Edition", "Java External Edition"},
                1,
                "JEE signifie Java Enterprise Edition, utilisé pour créer des applications de niveau entreprise."),
            new Question("Quelle est une application de bureau ?",
                new String[]{"Amazon", "VLC Media Player", "eBay", "Air France"},
                1,
                "VLC est une application de bureau ; les autres sont des applications web d'entreprise."),
            new Question("Quel serveur supporte EJB ?",
                new String[]{"Tomcat", "GlassFish", "Jetty", "Apache"},
                1,
                "GlassFish est un serveur Java EE complet avec support EJB."),
            new Question("Quel type d'application nécessite JEE ?",
                new String[]{"Applications simples", "Applications d'entreprise", "Applications mobiles", "Applications de bureau"},
                1,
                "JEE est conçu pour les applications d'entreprise complexes nécessitant des services avancés."),
            new Question("Quelle est la principale caractéristique de JEE ?",
                new String[]{"Simplicité", "Scalabilité et services d'entreprise", "Vitesse", "Compatibilité mobile"},
                1,
                "JEE offre la scalabilité et des services d'entreprise comme la gestion des transactions et la sécurité."),
            new Question("Quel serveur est uniquement un conteneur web ?",
                new String[]{"GlassFish", "Tomcat", "WildFly", "WebLogic"},
                1,
                "Tomcat est un conteneur web qui ne supporte pas tous les composants JEE comme EJB."),
            new Question("Quelle technologie fait partie de JEE ?",
                new String[]{"Servlets", "Swing", "JavaFX", "Android"},
                0,
                "Les Servlets sont un composant fondamental de JEE pour créer des applications web."),
            new Question("Quelle version de Java EE est maintenant appelée Jakarta EE ?",
                new String[]{"Java EE 5", "Java EE 7", "Java EE 8", "Toutes après Java EE 8"},
                3,
                "Depuis Java EE 8, la plateforme a été transférée à la Fondation Eclipse et s'appelle maintenant Jakarta EE."),
            new Question("Quel est l'avantage principal de JEE par rapport à Java SE ?",
                new String[]{"Meilleure performance", "Services d'entreprise intégrés", "Syntaxe simplifiée", "Compatibilité mobile"},
                1,
                "JEE fournit des services d'entreprise intégrés comme la gestion des transactions, la sécurité, et la messagerie."),
            new Question("Quelle API JEE est utilisée pour la persistance ?",
                new String[]{"JDBC", "JPA", "JNDI", "JMS"},
                1,
                "JPA (Java Persistence API) est l'API standard pour la persistance des objets Java."),
            new Question("Quel composant JEE gère les requêtes HTTP ?",
                new String[]{"EJB", "Servlet", "JSP", "JPA"},
                1,
                "Les Servlets gèrent les requêtes HTTP et génèrent des réponses dynamiques."),
            new Question("Quelle est la différence entre Java SE et Java EE ?",
                new String[]{"Aucune différence", "Java EE ajoute des APIs pour applications d'entreprise", "Java SE est plus rapide", "Java EE est pour mobile"},
                1,
                "Java EE étend Java SE avec des APIs spécialisées pour le développement d'applications d'entreprise."),
            new Question("Quel serveur d'application est développé par Red Hat ?",
                new String[]{"GlassFish", "WildFly", "Tomcat", "WebLogic"},
                1,
                "WildFly (anciennement JBoss) est développé par Red Hat."),
            new Question("Quelle spécification JEE définit les composants web ?",
                new String[]{"EJB", "Servlet", "JPA", "JMS"},
                1,
                "La spécification Servlet définit les composants web qui gèrent les requêtes HTTP."),
            new Question("Qu'est-ce qu'un EJB ?",
                new String[]{"Enterprise Java Bean", "Extended Java Build", "Enterprise Java Bundle", "External Java Base"},
                0,
                "EJB signifie Enterprise Java Bean, un composant côté serveur pour la logique métier."),
            new Question("Quelle API JEE permet la messagerie asynchrone ?",
                new String[]{"JDBC", "JPA", "JMS", "JNDI"},
                2,
                "JMS (Java Message Service) permet la communication asynchrone entre composants via des messages."),
            new Question("Quel est le rôle de JNDI dans JEE ?",
                new String[]{"Gérer les sessions", "Service de nommage et d'annuaire", "Gérer les transactions", "Gérer la sécurité"},
                1,
                "JNDI (Java Naming and Directory Interface) permet de localiser des ressources par leur nom."),
            new Question("Quelle technologie JEE est utilisée pour créer des pages web dynamiques ?",
                new String[]{"EJB", "Servlet", "JSP", "JPA"},
                2,
                "JSP (JavaServer Pages) permet de créer des pages web dynamiques en mélangeant HTML et Java."),
            new Question("Quel conteneur est nécessaire pour exécuter des Servlets ?",
                new String[]{"Conteneur EJB", "Conteneur Web", "Conteneur JPA", "Aucun conteneur"},
                1,
                "Les Servlets s'exécutent dans un conteneur web qui gère leur cycle de vie."),
            new Question("Quelle est la différence entre un conteneur web et un serveur d'application complet ?",
                new String[]{"Aucune différence", "Le serveur d'application inclut aussi un conteneur EJB", "Le conteneur web est plus puissant", "Le serveur d'application est gratuit"},
                1,
                "Un serveur d'application complet inclut à la fois un conteneur web et un conteneur EJB, contrairement à un simple conteneur web comme Tomcat.")
        ));
    }
}