import java.util.Arrays;

public class Chapter2 extends Chapter {
    public Chapter2() {
        super("Chapitre 2 : Architecture JEE", Arrays.asList(
            new Question("Quelle couche gère la logique métier ?",
                new String[]{"Présentation", "Métier", "Données", "Client"},
                1,
                "La couche Métier contient la logique, les règles et le traitement."),
            new Question("Quel est le principal avantage de l'architecture 3-tiers ?",
                new String[]{"Vitesse", "Centralisation", "Séparation des préoccupations", "Sécurité"},
                2,
                "Elle sépare les responsabilités entre les couches pour une meilleure maintenabilité."),
            new Question("Combien de couches composent l'architecture 3-tiers ?",
                new String[]{"2", "3", "4", "5"},
                1,
                "L'architecture 3-tiers comprend : Présentation, Métier et Données."),
            new Question("Quelle couche interagit directement avec l'utilisateur ?",
                new String[]{"Couche Métier", "Couche Présentation", "Couche Données", "Couche Client"},
                1,
                "La couche Présentation gère l'interface utilisateur et l'interaction."),
            new Question("Quelle couche gère l'accès aux bases de données ?",
                new String[]{"Présentation", "Métier", "Données", "Client"},
                2,
                "La couche Données gère la persistance et l'accès aux bases de données."),
            new Question("Quel est l'avantage de la séparation en couches ?",
                new String[]{"Performance", "Maintenabilité et évolutivité", "Sécurité uniquement", "Simplicité"},
                1,
                "La séparation permet une meilleure maintenabilité, testabilité et évolutivité du code."),
            new Question("Dans quelle couche se trouvent les Servlets ?",
                new String[]{"Couche Données", "Couche Métier", "Couche Présentation", "Couche Client"},
                2,
                "Les Servlets font partie de la couche Présentation, gérant les requêtes HTTP."),
            new Question("Quel est le modèle d'architecture le plus courant en JEE ?",
                new String[]{"1-tier", "2-tiers", "3-tiers", "4-tiers"},
                2,
                "L'architecture 3-tiers est le modèle standard pour les applications JEE."),
            new Question("Quelle couche est responsable de la validation des données ?",
                new String[]{"Uniquement Présentation", "Présentation et Métier", "Uniquement Données", "Toutes les couches"},
                1,
                "La validation peut se faire dans la couche Présentation (interface) et Métier (logique)."),
            new Question("Qu'est-ce qu'une architecture n-tiers ?",
                new String[]{"Architecture avec n serveurs", "Architecture avec plusieurs couches logiques", "Architecture avec n bases de données", "Architecture avec n clients"},
                1,
                "Une architecture n-tiers sépare l'application en plusieurs couches logiques distinctes."),
            new Question("Quelle couche contient généralement les EJB ?",
                new String[]{"Présentation", "Métier", "Données", "Client"},
                1,
                "Les EJB (Enterprise JavaBeans) sont des composants de la couche Métier."),
            new Question("Quel est l'avantage de séparer la logique métier de la présentation ?",
                new String[]{"Performance", "Réutilisabilité et maintenabilité", "Sécurité", "Simplicité"},
                1,
                "La séparation permet de réutiliser la logique métier avec différentes interfaces (web, mobile, etc.)."),
            new Question("Dans une architecture 3-tiers, où se trouve la base de données ?",
                new String[]{"Couche Présentation", "Couche Métier", "Couche Données", "Couche Client"},
                2,
                "La base de données fait partie de la couche Données (tier de persistance)."),
            new Question("Quelle est la responsabilité de la couche Présentation ?",
                new String[]{"Stocker les données", "Afficher l'interface et capturer les entrées utilisateur", "Traiter la logique métier", "Gérer les transactions"},
                1,
                "La couche Présentation gère l'affichage et l'interaction avec l'utilisateur."),
            new Question("Quelle technologie appartient à la couche Présentation ?",
                new String[]{"EJB", "JPA", "JSP", "JDBC"},
                2,
                "JSP (JavaServer Pages) fait partie de la couche Présentation pour générer des pages web dynamiques."),
            new Question("Quel pattern est souvent utilisé dans la couche Métier ?",
                new String[]{"MVC", "DAO", "Business Delegate", "Front Controller"},
                2,
                "Le pattern Business Delegate est couramment utilisé dans la couche Métier pour encapsuler la logique."),
            new Question("Quelle couche est responsable de l'authentification ?",
                new String[]{"Uniquement Présentation", "Présentation et Métier", "Uniquement Métier", "Uniquement Données"},
                1,
                "L'authentification se fait généralement dans les couches Présentation (capture) et Métier (vérification)."),
            new Question("Quel est le rôle du pattern DAO ?",
                new String[]{"Gérer l'interface utilisateur", "Abstraire l'accès aux données", "Gérer les sessions", "Gérer les transactions"},
                1,
                "DAO (Data Access Object) abstrait et encapsule l'accès à la source de données."),
            new Question("Dans quelle couche se fait le mapping objet-relationnel ?",
                new String[]{"Présentation", "Métier", "Données", "Client"},
                2,
                "Le mapping objet-relationnel (ORM) se fait dans la couche Données, souvent avec JPA."),
            new Question("Pourquoi séparer l'application en couches distinctes ?",
                new String[]{"Pour ralentir l'application", "Pour faciliter la maintenance et les tests", "Pour compliquer le code", "Pour augmenter la taille du projet"},
                1,
                "La séparation en couches facilite la maintenance, les tests unitaires, et permet de modifier une couche sans affecter les autres.")
        ));
    }
}