import java.util.Arrays;

public class Chapter13 extends Chapter {
    public Chapter13() {
        super("Chapitre 13 : Récapitulatif Final", Arrays.asList(
            new Question("Quel composant envoie la requête HTTP initiale ?",
                new String[]{"Servlet", "Navigateur", "Serveur", "Base de données"},
                1,
                "Le navigateur initie la requête HTTP lorsque l'utilisateur interagit avec l'application."),
            new Question("Quelle méthode est appelée pour gérer les requêtes GET dans un servlet ?",
                new String[]{"doPost()", "doGet()", "init()", "destroy()"},
                1,
                "doGet() est utilisée pour gérer les requêtes HTTP GET."),
            new Question("Quel est le rôle de la couche Métier dans l'architecture 3-tiers ?",
                new String[]{"Afficher l'interface", "Stocker les données", "Traiter la logique", "Gérer HTTP"},
                2,
                "La couche Métier traite la logique et les règles de l'application."),
            new Question("Quel fichier définit les mappings de servlets et les paramètres de session ?",
                new String[]{"application.xml", "pom.xml", "web.xml", "config.properties"},
                2,
                "web.xml est le descripteur de déploiement pour la configuration des servlets."),
            new Question("Que représente JSESSIONID ?",
                new String[]{"Rôle utilisateur", "Identifiant de session", "Type de requête", "Nom de cookie"},
                1,
                "JSESSIONID est un cookie utilisé pour suivre la session de l'utilisateur."),
            new Question("Quel conteneur gère les Servlets ?",
                new String[]{"Conteneur EJB", "Conteneur Web", "Conteneur JPA", "Conteneur JMS"},
                1,
                "Le Conteneur Web gère le cycle de vie des Servlets."),
            new Question("Quelle est la méthode du cycle de vie appelée en premier ?",
                new String[]{"doGet()", "init()", "service()", "destroy()"},
                1,
                "init() est appelée une fois lors de l'initialisation du servlet."),
            new Question("Quel format de fichier est utilisé pour déployer une application web ?",
                new String[]{"JAR", "WAR", "EAR", "ZIP"},
                1,
                "WAR (Web Application Archive) est utilisé pour déployer les applications web."),
            new Question("Comment récupérer un paramètre de requête dans un servlet ?",
                new String[]{"getAttribute()", "getParameter()", "getValue()", "getRequestParam()"},
                1,
                "getParameter() récupère un paramètre de la requête HTTP."),
            new Question("Quel code HTTP indique une redirection ?",
                new String[]{"200", "404", "302", "500"},
                2,
                "302 est le code de redirection HTTP."),
            new Question("Quelle est la première étape du cycle de vie d'un servlet ?",
                new String[]{"service()", "init()", "doGet()", "destroy()"},
                1,
                "init() est la première méthode appelée lors du cycle de vie d'un servlet."),
            new Question("Quel conteneur est nécessaire pour exécuter une application JEE complète ?",
                new String[]{"Uniquement conteneur web", "Conteneur web et EJB", "Uniquement conteneur EJB", "Aucun conteneur"},
                1,
                "Une application JEE complète nécessite à la fois un conteneur web et un conteneur EJB."),
            new Question("Quelle API JEE est utilisée pour la persistance des objets ?",
                new String[]{"JDBC", "JPA", "JNDI", "JMS"},
                1,
                "JPA (Java Persistence API) est l'API standard pour la persistance des objets Java."),
            new Question("Quel fichier est le descripteur de déploiement pour une application web ?",
                new String[]{"application.xml", "pom.xml", "web.xml", "deployment.xml"},
                2,
                "web.xml est le descripteur de déploiement standard pour les applications web JEE."),
            new Question("Quelle méthode HttpServletRequest récupère les paramètres de formulaire ?",
                new String[]{"getAttribute()", "getParameter()", "getValue()", "getFormData()"},
                1,
                "getParameter() récupère les paramètres envoyés via GET ou POST."),
            new Question("Quel est le rôle du conteneur web dans JEE ?",
                new String[]{"Gérer les bases de données", "Gérer le cycle de vie des Servlets et JSP", "Gérer les EJB", "Gérer les transactions"},
                1,
                "Le conteneur web gère le cycle de vie, la sécurité et les services pour les Servlets et JSP."),
            new Question("Quelle est la structure d'un fichier WAR ?",
                new String[]{"Uniquement des classes", "WEB-INF/ avec classes, lib, web.xml + ressources web publiques", "Uniquement web.xml", "Uniquement des JSP"},
                1,
                "Un WAR contient WEB-INF/ (classes, lib, web.xml) et les ressources web accessibles publiquement."),
            new Question("Comment une session HTTP est-elle identifiée ?",
                new String[]{"Par l'adresse IP", "Par le cookie JSESSIONID", "Par le nom d'utilisateur", "Par le navigateur"},
                1,
                "Le cookie JSESSIONID identifie de manière unique chaque session HTTP."),
            new Question("Quelle est la méthode principale pour gérer les requêtes dans un servlet ?",
                new String[]{"init()", "service()", "destroy()", "doGet()"},
                1,
                "service() est la méthode principale qui route les requêtes vers doGet(), doPost(), etc."),
            new Question("Félicitations ! Vous avez complété tous les chapitres. Quelle est la prochaine étape ?",
                new String[]{"Recommencer depuis le début", "Pratiquer avec des projets réels", "Abandonner JEE", "Rien faire"},
                1,
                "La meilleure façon de maîtriser JEE est de pratiquer en développant des projets réels !")
        ));
    }
}