import java.util.Arrays;

public class Chapter4 extends Chapter {
    public Chapter4() {
        super("Chapitre 4 : Serveurs d'Application", Arrays.asList(
            new Question("Quel port est couramment utilisé pour HTTP ?",
                new String[]{"21", "443", "80", "25"},
                2,
                "Le port 80 est le standard pour HTTP."),
            new Question("Quel service JNDI fournit-il ?",
                new String[]{"Messagerie", "Nommage", "Sécurité", "Persistance"},
                1,
                "JNDI gère les services de nommage et d'annuaire."),
            new Question("Quel port est utilisé pour HTTPS ?",
                new String[]{"80", "8080", "443", "8443"},
                2,
                "Le port 443 est le standard pour HTTPS (HTTP sécurisé)."),
            new Question("Qu'est-ce qu'un serveur d'application ?",
                new String[]{"Une base de données", "Un environnement d'exécution pour applications JEE", "Un navigateur", "Un système d'exploitation"},
                1,
                "Un serveur d'application fournit un environnement d'exécution pour les applications JEE."),
            new Question("Quel serveur est un serveur JEE complet ?",
                new String[]{"Tomcat", "GlassFish", "Jetty", "Nginx"},
                1,
                "GlassFish est un serveur JEE complet supportant tous les composants."),
            new Question("Que signifie JNDI ?",
                new String[]{"Java Network Data Interface", "Java Naming and Directory Interface", "Java Network Directory Interface", "Java Naming Data Interface"},
                1,
                "JNDI signifie Java Naming and Directory Interface."),
            new Question("Quel est l'avantage d'utiliser un serveur d'application ?",
                new String[]{"Vitesse uniquement", "Services intégrés (transactions, sécurité, pooling)", "Simplicité", "Compatibilité mobile"},
                1,
                "Les serveurs d'application offrent des services intégrés comme la gestion des transactions, la sécurité et le pooling de connexions."),
            new Question("Quel port par défaut utilise Tomcat ?",
                new String[]{"80", "443", "8080", "8443"},
                2,
                "Tomcat utilise le port 8080 par défaut pour HTTP."),
            new Question("Qu'est-ce que JNDI permet de faire ?",
                new String[]{"Envoyer des emails", "Trouver des ressources par nom", "Créer des servlets", "Gérer les sessions"},
                1,
                "JNDI permet de rechercher et d'accéder à des ressources (datasources, EJB, etc.) par leur nom."),
            new Question("Quel serveur est développé par Oracle ?",
                new String[]{"GlassFish", "WebLogic", "Tomcat", "WildFly"},
                1,
                "WebLogic est un serveur d'application développé par Oracle."),
            new Question("Quelle est la différence entre un serveur web et un serveur d'application ?",
                new String[]{"Aucune différence", "Le serveur d'application supporte plus de technologies JEE", "Le serveur web est plus rapide", "Le serveur d'application est gratuit"},
                1,
                "Un serveur d'application supporte plus de technologies JEE (EJB, JMS, etc.) qu'un simple serveur web."),
            new Question("Quel service permet de gérer les connexions à la base de données ?",
                new String[]{"JNDI", "JDBC", "Connection Pooling", "JMS"},
                2,
                "Le Connection Pooling permet de gérer un pool de connexions réutilisables à la base de données."),
            new Question("Qu'est-ce qu'un datasource ?",
                new String[]{"Une source de données", "Une configuration de connexion à la base de données", "Un fichier de données", "Une API de données"},
                1,
                "Un datasource est une configuration qui définit comment se connecter à une base de données."),
            new Question("Comment déployer une application sur un serveur d'application ?",
                new String[]{"Copier les fichiers", "Déployer un fichier WAR ou EAR", "Compiler seulement", "Installer un plugin"},
                1,
                "On déploie une application JEE en déployant un fichier WAR (web) ou EAR (entreprise) sur le serveur."),
            new Question("Quel serveur d'application est open source et développé par Eclipse Foundation ?",
                new String[]{"WebLogic", "GlassFish", "WebSphere", "Tomcat"},
                1,
                "GlassFish est open source et maintenu par la Eclipse Foundation."),
            new Question("Qu'est-ce que le hot deployment ?",
                new String[]{"Déployer dans un environnement chaud", "Déployer sans redémarrer le serveur", "Déployer rapidement", "Déployer avec Java"},
                1,
                "Le hot deployment permet de déployer ou mettre à jour une application sans redémarrer le serveur."),
            new Question("Quel est le port par défaut pour l'administration de GlassFish ?",
                new String[]{"4848", "8080", "8181", "9090"},
                0,
                "GlassFish utilise le port 4848 pour la console d'administration par défaut."),
            new Question("Qu'est-ce qu'un cluster de serveurs ?",
                new String[]{"Un seul serveur puissant", "Plusieurs serveurs travaillant ensemble", "Un type de base de données", "Un conteneur spécial"},
                1,
                "Un cluster est un groupe de serveurs d'application travaillant ensemble pour la haute disponibilité et la scalabilité."),
            new Question("Quel serveur d'application était anciennement appelé JBoss ?",
                new String[]{"GlassFish", "WildFly", "WebLogic", "Payara"},
                1,
                "WildFly est le nouveau nom de JBoss Application Server, développé par Red Hat."),
            new Question("Qu'est-ce que le load balancing dans un serveur d'application ?",
                new String[]{"Équilibrer le budget", "Répartir la charge entre plusieurs serveurs", "Charger plus rapidement", "Balancer les données"},
                1,
                "Le load balancing distribue les requêtes entrantes entre plusieurs instances de serveurs pour optimiser les performances.")
        ));
    }
}