import java.util.Arrays;

public class Chapter9 extends Chapter {
    public Chapter9() {
        super("Chapitre 9 : Maven et Gradle", Arrays.asList(
            new Question("Quel est le fichier de configuration de Maven ?",
                new String[]{"build.gradle", "pom.xml", "config.xml", "project.xml"},
                1,
                "pom.xml est le fichier de configuration de Maven."),
            new Question("Quel dossier contient les ressources web ?",
                new String[]{"src/main/webapp", "src/resources", "src/html", "src/public"},
                0,
                "src/main/webapp contient HTML, JSP, CSS."),
            new Question("Que signifie POM ?",
                new String[]{"Project Object Model", "Program Object Management", "Project Organization Model", "Program Organization Management"},
                0,
                "POM signifie Project Object Model, le modèle de projet Maven."),
            new Question("Quel est le fichier de configuration de Gradle ?",
                new String[]{"pom.xml", "build.gradle", "gradle.xml", "config.gradle"},
                1,
                "build.gradle est le fichier de configuration principal de Gradle."),
            new Question("Quel dossier contient le code source Java dans Maven ?",
                new String[]{"src/java", "src/main/java", "src/classes", "java/"},
                1,
                "src/main/java contient le code source Java dans un projet Maven."),
            new Question("Quel dossier contient les tests dans Maven ?",
                new String[]{"src/test/java", "test/", "src/tests", "tests/"},
                0,
                "src/test/java contient les tests unitaires dans Maven."),
            new Question("Quelle commande Maven compile le projet ?",
                new String[]{"maven build", "mvn compile", "maven compile", "mvn build"},
                1,
                "mvn compile compile le code source Java du projet."),
            new Question("Quelle commande Maven crée un WAR ?",
                new String[]{"mvn war", "mvn package", "mvn build", "mvn deploy"},
                1,
                "mvn package compile, teste et crée le fichier WAR dans target/."),
            new Question("Où Maven stocke-t-il les fichiers compilés ?",
                new String[]{"src/", "target/", "build/", "out/"},
                1,
                "Maven stocke tous les fichiers générés dans le dossier target/."),
            new Question("Quelle est la structure standard d'un projet Maven ?",
                new String[]{"src/ et pom.xml", "src/main/java, src/main/resources, src/test/java, pom.xml", "Uniquement pom.xml", "src/ et build.xml"},
                1,
                "Un projet Maven standard a src/main/java, src/main/resources, src/test/java et pom.xml."),
            new Question("Qu'est-ce qu'un repository Maven ?",
                new String[]{"Un serveur de base de données", "Un dépôt de bibliothèques JAR", "Un serveur web", "Un système de fichiers"},
                1,
                "Un repository Maven stocke et distribue les bibliothèques JAR et leurs métadonnées."),
            new Question("Quelle commande Gradle compile le projet ?",
                new String[]{"gradle compile", "gradle build", "gradle run", "gradle test"},
                1,
                "gradle build compile, teste et crée les artefacts du projet."),
            new Question("Quelle est la différence principale entre Maven et Gradle ?",
                new String[]{"Aucune différence", "Gradle utilise un DSL Groovy/Kotlin, Maven utilise XML", "Maven est plus rapide", "Gradle est plus ancien"},
                1,
                "Gradle utilise un DSL (Groovy/Kotlin) plus flexible, tandis que Maven utilise XML."),
            new Question("Quel fichier définit les dépendances dans Gradle ?",
                new String[]{"pom.xml", "build.gradle", "dependencies.gradle", "config.gradle"},
                1,
                "build.gradle contient la section dependencies qui liste les dépendances."),
            new Question("Quelle commande Maven nettoie le projet (supprime target/) ?",
                new String[]{"mvn clean", "mvn delete", "mvn remove", "mvn clear"},
                0,
                "mvn clean supprime le dossier target/ et tous les fichiers générés."),
            new Question("Qu'est-ce que Maven Central ?",
                new String[]{"Un serveur Maven", "Le repository public principal de Maven", "Un plugin Maven", "Une commande Maven"},
                1,
                "Maven Central est le repository public principal où sont hébergées la plupart des bibliothèques Java."),
            new Question("Quelle commande Maven exécute les tests ?",
                new String[]{"mvn run-tests", "mvn test", "mvn check", "mvn verify"},
                1,
                "mvn test compile et exécute les tests unitaires du projet."),
            new Question("Que fait la commande 'mvn install' ?",
                new String[]{"Installe Maven", "Compile, teste et installe l'artefact dans le repository local", "Installe les dépendances", "Installe le serveur"},
                1,
                "mvn install compile, teste le projet et installe l'artefact dans le repository local (~/.m2/repository)."),
            new Question("Où Gradle stocke-t-il les fichiers compilés ?",
                new String[]{"target/", "build/", "out/", "bin/"},
                1,
                "Gradle stocke les fichiers générés dans le dossier build/ par défaut."),
            new Question("Quelle section du pom.xml définit les informations du projet ?",
                new String[]{"<project>", "<groupId>, <artifactId>, <version>", "<info>", "<metadata>"},
                1,
                "Les balises <groupId>, <artifactId> et <version> définissent l'identité unique du projet Maven.")
        ));
    }
}