import java.util.Arrays;

public class Chapter12 extends Chapter {
    public Chapter12() {
        super("Chapitre 12 : Réponses HTTP et Sessions", Arrays.asList(
            new Question("Quel cookie suit l'ID de session ?",
                new String[]{"SESSIONID", "JSESSIONID", "COOKIEID", "USERID"},
                1,
                "JSESSIONID identifie la session de l'utilisateur."),
            new Question("Que signifie le statut HTTP 200 ?",
                new String[]{"Non trouvé", "OK", "Erreur", "Redirection"},
                1,
                "200 OK signifie une réponse réussie."),
            new Question("Comment définir le type de contenu de la réponse ?",
                new String[]{"setContent()", "setContentType()", "setType()", "setMimeType()"},
                1,
                "setContentType() définit le type MIME de la réponse (ex: text/html)."),
            new Question("Quel code HTTP signifie 'Non trouvé' ?",
                new String[]{"200", "404", "500", "302"},
                1,
                "404 signifie que la ressource demandée n'a pas été trouvée."),
            new Question("Comment obtenir l'objet session dans un servlet ?",
                new String[]{"getSession()", "createSession()", "new Session()", "getHttpSession()"},
                0,
                "getSession() retourne l'objet HttpSession associé à la requête."),
            new Question("Comment stocker une valeur dans la session ?",
                new String[]{"setValue()", "setAttribute()", "put()", "store()"},
                1,
                "setAttribute() stocke un attribut dans l'objet session."),
            new Question("Quel code HTTP signifie 'Erreur serveur' ?",
                new String[]{"400", "404", "500", "302"},
                2,
                "500 signifie une erreur interne du serveur."),
            new Question("Comment rediriger vers une autre page ?",
                new String[]{"forward()", "redirect()", "sendRedirect()", "navigate()"},
                2,
                "sendRedirect() envoie une redirection HTTP au client."),
            new Question("Quelle est la différence entre forward() et sendRedirect() ?",
                new String[]{"Aucune différence", "forward() est côté serveur, sendRedirect() envoie une réponse au client", "sendRedirect() est côté serveur", "forward() envoie une réponse"},
                1,
                "forward() transfère la requête côté serveur, sendRedirect() envoie une réponse de redirection au client."),
            new Question("Comment obtenir un attribut de session ?",
                new String[]{"getValue()", "getAttribute()", "getSessionAttribute()", "get()"},
                1,
                "getAttribute() récupère un attribut stocké dans la session."),
            new Question("Comment supprimer un attribut de session ?",
                new String[]{"remove()", "removeAttribute()", "delete()", "clear()"},
                1,
                "removeAttribute() supprime un attribut spécifique de la session."),
            new Question("Comment invalider une session ?",
                new String[]{"destroy()", "invalidate()", "end()", "close()"},
                1,
                "invalidate() détruit la session et libère toutes ses données."),
            new Question("Quel code HTTP signifie 'Requête incorrecte' ?",
                new String[]{"200", "400", "404", "500"},
                1,
                "400 Bad Request signifie que la requête est mal formée."),
            new Question("Quel code HTTP signifie 'Non autorisé' ?",
                new String[]{"400", "401", "403", "404"},
                1,
                "401 Unauthorized signifie que l'authentification est requise."),
            new Question("Comment écrire du texte dans la réponse HTTP ?",
                new String[]{"write()", "getWriter()", "getOutputStream()", "print()"},
                1,
                "response.getWriter() retourne un PrintWriter pour écrire du texte dans la réponse."),
            new Question("Quelle méthode définit le code de statut HTTP ?",
                new String[]{"setStatus()", "setStatusCode()", "setHttpStatus()", "status()"},
                0,
                "setStatus() définit le code de statut HTTP de la réponse."),
            new Question("Comment ajouter un cookie à la réponse ?",
                new String[]{"setCookie()", "addCookie()", "putCookie()", "createCookie()"},
                1,
                "addCookie() ajoute un cookie à la réponse HTTP."),
            new Question("Quel code HTTP signifie 'Accès interdit' ?",
                new String[]{"401", "403", "404", "500"},
                1,
                "403 Forbidden signifie que l'accès à la ressource est interdit même avec authentification."),
            new Question("Comment ajouter un en-tête personnalisé à la réponse ?",
                new String[]{"addHeader()", "setHeader()", "putHeader()", "Les deux premières réponses"},
                3,
                "addHeader() et setHeader() permettent d'ajouter des en-têtes HTTP personnalisés à la réponse."),
            new Question("Quelle méthode permet d'obtenir l'ID de la session ?",
                new String[]{"getSessionId()", "getId()", "getSessionID()", "getIdentifier()"},
                1,
                "session.getId() retourne l'identifiant unique de la session (le JSESSIONID).")
        ));
    }
}