import java.util.Arrays;

public class Chapter6 extends Chapter {
    public Chapter6() {
        super("Chapitre 6 : Configuration web.xml", Arrays.asList(
            new Question("Quelle balise mappe un servlet à une URL ?",
                new String[]{"<servlet>", "<url-map>", "<servlet-mapping>", "<web-app>"},
                2,
                "<servlet-mapping> définit les motifs d'URL pour les servlets."),
            new Question("Quelle balise définit la page d'accueil ?",
                new String[]{"<welcome-file-list>", "<home>", "<index>", "<default-page>"},
                0,
                "<welcome-file-list> définit les pages d'accueil par défaut."),
            new Question("Quelle est la balise racine de web.xml ?",
                new String[]{"<servlet>", "<web-app>", "<application>", "<config>"},
                1,
                "<web-app> est l'élément racine du fichier web.xml."),
            new Question("Quelle balise déclare un servlet ?",
                new String[]{"<servlet-mapping>", "<servlet>", "<servlet-class>", "<url-pattern>"},
                1,
                "<servlet> déclare un servlet avec son nom et sa classe."),
            new Question("Quelle balise définit le pattern d'URL dans servlet-mapping ?",
                new String[]{"<servlet-name>", "<url-pattern>", "<mapping>", "<path>"},
                1,
                "<url-pattern> définit le motif d'URL qui déclenchera le servlet."),
            new Question("Quelle balise définit les paramètres d'initialisation d'un servlet ?",
                new String[]{"<param>", "<init-param>", "<servlet-param>", "<config-param>"},
                1,
                "<init-param> définit les paramètres d'initialisation dans la déclaration du servlet."),
            new Question("Quelle balise définit les filtres ?",
                new String[]{"<filter>", "<servlet-filter>", "<web-filter>", "<http-filter>"},
                0,
                "<filter> déclare un filtre qui peut intercepter les requêtes avant qu'elles n'atteignent le servlet."),
            new Question("Quelle balise mappe un filtre à une URL ?",
                new String[]{"<filter>", "<filter-mapping>", "<url-filter>", "<filter-url>"},
                1,
                "<filter-mapping> associe un filtre à un pattern d'URL."),
            new Question("Quelle balise définit le nom d'un servlet ?",
                new String[]{"<servlet-name>", "<name>", "<servlet-class>", "<class>"},
                0,
                "<servlet-name> définit le nom unique du servlet dans web.xml."),
            new Question("Quelle balise définit la classe du servlet ?",
                new String[]{"<servlet-name>", "<servlet-class>", "<class>", "<servlet>"},
                1,
                "<servlet-class> spécifie le nom complet de la classe du servlet."),
            new Question("Quel pattern d'URL correspond à toutes les URLs ?",
                new String[]{"/*", "/", "*", "all"},
                0,
                "Le pattern /* correspond à toutes les URLs de l'application."),
            new Question("Quelle balise définit plusieurs pages d'accueil ?",
                new String[]{"<welcome-file>", "<welcome-file-list>", "<index>", "<home>"},
                1,
                "<welcome-file-list> peut contenir plusieurs <welcome-file> pour définir l'ordre de recherche."),
            new Question("Où doit être placé web.xml dans un projet Maven ?",
                new String[]{"src/main/java", "src/main/webapp/WEB-INF/", "src/main/resources", "src/test"},
                1,
                "web.xml doit être dans src/main/webapp/WEB-INF/ pour un projet Maven."),
            new Question("Quelle est la version XML minimale pour web.xml moderne ?",
                new String[]{"2.3", "3.0", "3.1", "4.0"},
                2,
                "La version 3.1 ou supérieure est recommandée pour les applications JEE modernes."),
            new Question("Quelle balise définit l'ordre de chargement des servlets ?",
                new String[]{"<load-order>", "<load-on-startup>", "<startup-order>", "<init-order>"},
                1,
                "<load-on-startup> définit l'ordre de chargement des servlets au démarrage du conteneur."),
            new Question("Que signifie <load-on-startup>1</load-on-startup> ?",
                new String[]{"Charger après 1 seconde", "Charger en premier au démarrage", "Charger 1 fois", "Erreur de configuration"},
                1,
                "Une valeur positive indique que le servlet doit être chargé au démarrage, les plus petites valeurs sont chargées en premier."),
            new Question("Quelle balise définit les pages d'erreur personnalisées ?",
                new String[]{"<error>", "<error-page>", "<custom-error>", "<error-handler>"},
                1,
                "<error-page> permet de mapper des codes d'erreur HTTP à des pages personnalisées."),
            new Question("Comment définir un filtre qui s'applique à tous les servlets ?",
                new String[]{"<url-pattern>*</url-pattern>", "<url-pattern>/*</url-pattern>", "<servlet-name>*</servlet-name>", "Impossible"},
                1,
                "Dans <filter-mapping>, utiliser <url-pattern>/*</url-pattern> applique le filtre à toutes les URLs."),
            new Question("Quelle balise définit les contraintes de sécurité ?",
                new String[]{"<security>", "<security-constraint>", "<auth>", "<protected>"},
                1,
                "<security-constraint> définit les règles de sécurité pour protéger certaines ressources."),
            new Question("Depuis quelle version de Servlet peut-on utiliser les annotations au lieu de web.xml ?",
                new String[]{"2.5", "3.0", "3.1", "4.0"},
                1,
                "Servlet 3.0 a introduit les annotations (@WebServlet, @WebFilter) comme alternative à web.xml.")
        ));
    }
}